version: '3'

services:
  db:
    env_file:
      - db.env
    image: postgres:alpine
    restart: always
    volumes:
      - /docker/private-cloud/postgresql:/var/lib/postgresql/data
  app:
    image: nextcloud:apache
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=nextcloud
    env_file:
      - db.env
    ports:
      - 8080:80
    restart: always
    volumes:
      - /docker/private-cloud/nextcloud:/var/www/html
